version: '3.6'
services:
  web:
    restart: always 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./prisma/
        target: /app/prisma/
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local