version: '3.6'
services:
  web:
    restart: always 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src/
        target: /app/src/
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*